version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      # DOMAINS: 'test.com(yourdomain) -> http://web:8000'
      DOMAINS: 'localhost -> http://web:8000'
      STAGE: local
      CLIENT_MAX_BODY_SIZE: 10M
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      # - ${WEB_PORT}:80
      - 8000:8000
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html
      - ./logs:/var/log/nginx

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
