version: '3.8'

volumes:
  mysql-volume:
  node_modules:

services:
  app:
    container_name: gaia_app_1
    build:
      args:
        user: master
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
      # - ./docker/cron:/etc/cron.d
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  
  cron:
    container_name: gaia_cron_1
    build: ./docker/cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'localhost -> http://web:80'
      # DOMAINS: 'areas-kk.com -> http://web:80' #本番用
      STAGE: local
      # STAGE: production #本番用
      CLIENT_MAX_BODY_SIZE: 10M
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - gaia-app-1
    volumes:
      - ./src/:/var/www/html
      - ./logs:/var/log/nginx

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  python:
    container_name: gaia_python_1
    restart: always
    shm_size: 2gb
    # links:
    #   - selenium-hub:hub
    tty: true
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      #- ./docker/python/crontab:/var/spool/cron/crontabs/root
      - ./src/:/var/www/html
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome
    container_name: chrome
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
    # volumes:
    #   - /dev/shm:/dev/shm
