version: '3.8'

volumes:
  mysql-volume:
  node_modules:

services:
  app:
    container_name: gaia-app-1
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
      - ./cron:/etc/cron.d
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'localhost -> http://web:80'
      STAGE: local
      CLIENT_MAX_BODY_SIZE: 10M
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - gaia_app
    volumes:
      - ./src/:/var/www/html
      - ./logs:/var/log/nginx

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  python:
    container_name: gaia-python-1
    restart: always
    tty: true
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.5"
          # CPU使用率を１コアの５０％に
          # 例：４コアで80％にしたい場合は3.2に
          # 注意点として、docker-compose up 時に --compatibility を付る必要があります。
          # docker compose --compatibility up -d
    volumes:
      #- ./docker/python/crontab:/var/spool/cron/crontabs/root
      - ./src/:/var/www/html
